name: Checks for pull request

on:
  pull_request:
    branches: [ "development" ]
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

# Jfrog artifactory login   
    - name: Login to DockerHub Registry, build and push
      run: |
          docker login -u ${{ secrets.JFROG_REGISTRY_USERNAME }} -p ${{ secrets.JFROG_REGISTRY_PASSWORD }} automotiveproject.jfrog.io
          docker build . -t automotiveproject.jfrog.io/docker-local/springboot-app:${{ github.run_number }}
          docker push automotiveproject.jfrog.io/docker-local/springboot-app:${{ github.run_number }}

